# The backend does not call the Kubernetes API. Explicitly using this Service
# Account prevents the default account token from being mounted implicitly.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-backend
automountServiceAccountToken: false
